/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.xemocode.demo.icons;

/**
 *
 * @author Saif
 */
public class hire_and_payment extends javax.swing.JFrame {

    /**
     * Creates new form hire_and_payment
     */
    public hire_and_payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jTextField7 = new javax.swing.JTextField();
        jButton38 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jButton44 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("Electrical Service");
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 140, -1));

        jButton28.setText("Cleaner");
        jPanel4.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jButton32.setText("Nurse");
        jPanel4.add(jButton32, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jButton33.setText("Maid");
        jPanel4.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jButton34.setText("Plumbing");
        jPanel4.add(jButton34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, 21));

        jButton35.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton35.setText("Log Out");
        jButton35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton35ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton35, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jTextField6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField6.setText("Customer Care");
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 850, 150, -1));

        jButton36.setText("Help Center");
        jPanel4.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 880, -1, -1));

        jButton37.setText("Complain Box");
        jPanel4.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 910, 93, -1));

        jTextField7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField7.setText("About Us");
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 850, 100, -1));

        jButton38.setText("Utility Service Provider");
        jPanel4.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 880, -1, -1));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, 60, 40));

        jButton44.setText("Contact Us");
        jPanel4.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 910, 93, -1));

        jButton57.setBackground(new java.awt.Color(0, 153, 153));
        jButton57.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("Utility Service Provider");
        jPanel4.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 480, -1));

        jButton61.setBackground(new java.awt.Color(204, 0, 0));
        jButton61.setFont(new java.awt.Font("Imprint MT Shadow", 1, 16)); // NOI18N
        jButton61.setForeground(new java.awt.Color(255, 255, 255));
        jButton61.setText("Become Worker");
        jPanel4.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jButton62.setText("Technological Service");
        jPanel4.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Welcome to Utility Services, your trusted partner in simplifying everyday tasks and making your life more \nconvenient. Our mission is to provide you with easy access to essential services, so you can focus on what \nmatters most.\nAt Utility Services, we are committed to simplifying your life by providing a comprehensive platform for all \nyour utility needs. Our mission is to make everyday tasks easier, more convenient, and more efficient.");
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 570, -1));

        jTextField2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTextField2.setText("About Us");
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 110, 40));

        jTextField3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTextField3.setText("Who We are");
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 130, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("At Utility Services, we are a passionate team dedicated to enhancing your daily experiences. We understand \nthe challenges of managing various household and personal tasks, and we believe that technology can \nmake a difference. Our app was born out of a desire to streamline your life and bring efficiency to your \nfingertips.");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 570, -1));

        jLabel1.setBackground(new java.awt.Color(153, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Admin");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 130, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(816, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 947, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(305, 305, 305))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton35ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(hire_and_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(hire_and_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(hire_and_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(hire_and_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new hire_and_payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
