/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.xemocode.demo;

/**
 *
 * @author Saif
 */
public class Index extends javax.swing.JFrame {

    /**
     * Creates new form Index
     */
    public Index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jButton72 = new javax.swing.JButton();
        jButton74 = new javax.swing.JButton();
        jButton75 = new javax.swing.JButton();
        jButton76 = new javax.swing.JButton();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jButton83 = new javax.swing.JButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton91 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jButton109 = new javax.swing.JButton();
        jButton73 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton87 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton88 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton89 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton86 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton90 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton92 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton93 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton94 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jButton95 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jButton96 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton97 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jButton110 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jButton111 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jButton114 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jButton115 = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jButton116 = new javax.swing.JButton();
        jButton117 = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(825, 1490));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Electrical Service");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jButton3.setText("Cleaner");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, -1, -1));

        jButton4.setText("Nurse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, -1, -1));

        jButton5.setText("Maid");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, -1, -1));

        jButton6.setText("Plumbing");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, -1, 20));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 70, -1, 30));

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField1.setText("Customer Care");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1310, 150, -1));

        jButton8.setText("Help Center");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1350, -1, -1));

        jButton9.setText("Complain Box");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1390, 120, -1));

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField2.setText("About Us");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1310, 100, -1));

        jButton11.setText("Utility Service Provider");
        jPanel1.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1350, -1, -1));

        jButton12.setBackground(new java.awt.Color(204, 0, 0));
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("HIRE");
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 60, -1));

        jButton13.setBackground(new java.awt.Color(204, 0, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("HIRE");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 60, -1));

        jButton14.setBackground(new java.awt.Color(204, 0, 0));
        jButton14.setForeground(new java.awt.Color(255, 255, 255));
        jButton14.setText("HIRE");
        jPanel1.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 60, -1));

        jButton15.setBackground(new java.awt.Color(204, 0, 0));
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("HIRE");
        jPanel1.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 60, -1));

        jButton16.setBackground(new java.awt.Color(204, 0, 0));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("HIRE");
        jPanel1.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, 60, -1));

        jButton17.setText("Contact Us");
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 1390, 110, -1));

        jButton18.setBackground(new java.awt.Color(204, 0, 0));
        jButton18.setForeground(new java.awt.Color(255, 255, 255));
        jButton18.setText("HIRE");
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 60, -1));

        jButton19.setBackground(new java.awt.Color(204, 0, 0));
        jButton19.setForeground(new java.awt.Color(255, 255, 255));
        jButton19.setText("HIRE");
        jPanel1.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 60, -1));

        jButton20.setBackground(new java.awt.Color(204, 0, 0));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("HIRE");
        jPanel1.add(jButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 430, 60, -1));

        jButton21.setBackground(new java.awt.Color(204, 0, 0));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("HIRE");
        jPanel1.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 60, -1));

        jButton22.setBackground(new java.awt.Color(204, 0, 0));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("HIRE");
        jPanel1.add(jButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 60, -1));

        jButton23.setBackground(new java.awt.Color(204, 0, 0));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("HIRE");
        jPanel1.add(jButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 60, -1));

        jButton24.setBackground(new java.awt.Color(204, 0, 0));
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("HIRE");
        jPanel1.add(jButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 600, 60, -1));

        jButton25.setBackground(new java.awt.Color(204, 0, 0));
        jButton25.setForeground(new java.awt.Color(255, 255, 255));
        jButton25.setText("HIRE");
        jPanel1.add(jButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 600, 60, -1));

        jButton26.setBackground(new java.awt.Color(204, 0, 0));
        jButton26.setForeground(new java.awt.Color(255, 255, 255));
        jButton26.setText("HIRE");
        jPanel1.add(jButton26, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 600, 60, -1));

        jButton27.setBackground(new java.awt.Color(204, 0, 0));
        jButton27.setForeground(new java.awt.Color(255, 255, 255));
        jButton27.setText("HIRE");
        jPanel1.add(jButton27, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 60, -1));

        jButton10.setBackground(new java.awt.Color(0, 153, 153));
        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Utility Service Provider");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 530, -1));

        jButton29.setBackground(new java.awt.Color(204, 0, 0));
        jButton29.setForeground(new java.awt.Color(255, 255, 255));
        jButton29.setText("HIRE");
        jButton29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton29ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 60, -1));

        jButton30.setBackground(new java.awt.Color(204, 0, 0));
        jButton30.setForeground(new java.awt.Color(255, 255, 255));
        jButton30.setText("HIRE");
        jButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 60, -1));

        jButton31.setBackground(new java.awt.Color(204, 0, 0));
        jButton31.setForeground(new java.awt.Color(255, 255, 255));
        jButton31.setText("HIRE");
        jButton31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton31ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 60, -1));

        jButton53.setBackground(new java.awt.Color(204, 0, 0));
        jButton53.setFont(new java.awt.Font("Imprint MT Shadow", 1, 16)); // NOI18N
        jButton53.setForeground(new java.awt.Color(255, 255, 255));
        jButton53.setText("Become Worker");
        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 40));

        jButton46.setText("Technological Service");
        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton46, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jButton33.setBackground(new java.awt.Color(204, 0, 0));
        jButton33.setForeground(new java.awt.Color(204, 204, 204));
        jButton33.setText("more.....");
        jButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton33, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 1150, 70, -1));

        jButton37.setBackground(new java.awt.Color(204, 0, 0));
        jButton37.setForeground(new java.awt.Color(255, 255, 255));
        jButton37.setText("HIRE");
        jPanel1.add(jButton37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1170, 60, -1));

        jButton38.setBackground(new java.awt.Color(204, 0, 0));
        jButton38.setForeground(new java.awt.Color(255, 255, 255));
        jButton38.setText("HIRE");
        jPanel1.add(jButton38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 990, 60, -1));

        jButton39.setBackground(new java.awt.Color(204, 0, 0));
        jButton39.setForeground(new java.awt.Color(255, 255, 255));
        jButton39.setText("HIRE");
        jPanel1.add(jButton39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 60, -1));

        jButton40.setBackground(new java.awt.Color(204, 0, 0));
        jButton40.setForeground(new java.awt.Color(255, 255, 255));
        jButton40.setText("HIRE");
        jPanel1.add(jButton40, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 800, 60, -1));

        jButton41.setBackground(new java.awt.Color(204, 0, 0));
        jButton41.setForeground(new java.awt.Color(255, 255, 255));
        jButton41.setText("HIRE");
        jPanel1.add(jButton41, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 800, 60, -1));

        jButton42.setBackground(new java.awt.Color(204, 0, 0));
        jButton42.setForeground(new java.awt.Color(255, 255, 255));
        jButton42.setText("HIRE");
        jPanel1.add(jButton42, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 800, 60, -1));

        jButton43.setBackground(new java.awt.Color(204, 0, 0));
        jButton43.setForeground(new java.awt.Color(255, 255, 255));
        jButton43.setText("HIRE");
        jPanel1.add(jButton43, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 800, 60, -1));

        jButton44.setBackground(new java.awt.Color(204, 0, 0));
        jButton44.setForeground(new java.awt.Color(255, 255, 255));
        jButton44.setText("HIRE");
        jPanel1.add(jButton44, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 800, 60, -1));

        jButton45.setBackground(new java.awt.Color(204, 0, 0));
        jButton45.setForeground(new java.awt.Color(204, 204, 204));
        jButton45.setText("more.....");
        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton45, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 70, -1));

        jButton47.setBackground(new java.awt.Color(204, 0, 0));
        jButton47.setForeground(new java.awt.Color(255, 255, 255));
        jButton47.setText("HIRE");
        jPanel1.add(jButton47, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 990, 60, -1));

        jButton48.setBackground(new java.awt.Color(204, 0, 0));
        jButton48.setForeground(new java.awt.Color(255, 255, 255));
        jButton48.setText("HIRE");
        jPanel1.add(jButton48, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 990, 60, -1));

        jButton49.setBackground(new java.awt.Color(204, 0, 0));
        jButton49.setForeground(new java.awt.Color(255, 255, 255));
        jButton49.setText("HIRE");
        jPanel1.add(jButton49, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 990, 60, -1));

        jButton50.setBackground(new java.awt.Color(204, 0, 0));
        jButton50.setForeground(new java.awt.Color(255, 255, 255));
        jButton50.setText("HIRE");
        jPanel1.add(jButton50, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 990, 60, -1));

        jButton51.setBackground(new java.awt.Color(204, 0, 0));
        jButton51.setForeground(new java.awt.Color(255, 255, 255));
        jButton51.setText("HIRE");
        jPanel1.add(jButton51, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 990, 60, -1));

        jButton52.setBackground(new java.awt.Color(204, 0, 0));
        jButton52.setForeground(new java.awt.Color(255, 255, 255));
        jButton52.setText("HIRE");
        jPanel1.add(jButton52, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1170, 60, -1));

        jButton54.setBackground(new java.awt.Color(204, 0, 0));
        jButton54.setForeground(new java.awt.Color(255, 255, 255));
        jButton54.setText("HIRE");
        jPanel1.add(jButton54, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 1170, 60, -1));

        jButton55.setBackground(new java.awt.Color(204, 0, 0));
        jButton55.setForeground(new java.awt.Color(255, 255, 255));
        jButton55.setText("HIRE");
        jPanel1.add(jButton55, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1170, 60, -1));

        jButton56.setBackground(new java.awt.Color(204, 0, 0));
        jButton56.setForeground(new java.awt.Color(255, 255, 255));
        jButton56.setText("HIRE");
        jPanel1.add(jButton56, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1170, 60, -1));

        jButton57.setBackground(new java.awt.Color(204, 0, 0));
        jButton57.setForeground(new java.awt.Color(255, 255, 255));
        jButton57.setText("HIRE");
        jPanel1.add(jButton57, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1170, 60, -1));

        jButton59.setBackground(new java.awt.Color(204, 0, 0));
        jButton59.setForeground(new java.awt.Color(204, 204, 204));
        jButton59.setText("more.....");
        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton59, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 70, -1));

        jButton60.setBackground(new java.awt.Color(204, 0, 0));
        jButton60.setForeground(new java.awt.Color(204, 204, 204));
        jButton60.setText("more.....");
        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton60, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 580, 70, -1));

        jButton61.setBackground(new java.awt.Color(204, 0, 0));
        jButton61.setForeground(new java.awt.Color(204, 204, 204));
        jButton61.setText("more.....");
        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton61, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 970, 70, -1));

        jButton62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton62.setText("jButton62");
        jPanel1.add(jButton62, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 60, 40));

        jButton63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton63.setText("jButton62");
        jPanel1.add(jButton63, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 40));

        jButton64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton64.setText("jButton62");
        jPanel1.add(jButton64, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 60, 40));

        jButton65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton65.setText("jButton62");
        jPanel1.add(jButton65, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 60, 40));

        jButton66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton66.setText("jButton62");
        jPanel1.add(jButton66, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, 60, 40));

        jButton67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton67.setText("jButton62");
        jPanel1.add(jButton67, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 60, 40));

        jButton68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton68.setText("jButton62");
        jPanel1.add(jButton68, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 60, 40));

        jButton69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton69.setText("jButton62");
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton69, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 60, 40));

        jButton70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton70.setText("jButton62");
        jPanel1.add(jButton70, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 60, 40));

        jButton71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton71.setText("jButton62");
        jPanel1.add(jButton71, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 60, 40));

        jButton72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton72.setText("jButton62");
        jPanel1.add(jButton72, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 60, 40));

        jButton74.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton74.setText("jButton62");
        jPanel1.add(jButton74, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 750, 60, 40));

        jButton75.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton75.setText("jButton62");
        jPanel1.add(jButton75, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 750, 60, 40));

        jButton76.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton76.setText("jButton62");
        jPanel1.add(jButton76, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 750, 60, 40));

        jButton77.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton77.setText("jButton62");
        jPanel1.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 750, 60, 40));

        jButton78.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton78.setText("jButton62");
        jPanel1.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 750, 60, 40));

        jButton79.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton79.setText("jButton62");
        jPanel1.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 750, 60, 40));

        jButton80.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton80.setText("jButton62");
        jPanel1.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 550, 60, 40));

        jButton81.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton81.setText("jButton62");
        jPanel1.add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 60, 40));

        jButton82.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton82.setText("jButton62");
        jPanel1.add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 550, 60, 40));

        jButton83.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton83.setText("jButton62");
        jPanel1.add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, 60, 40));

        jButton84.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton84.setText("jButton62");
        jPanel1.add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 550, 60, 40));

        jButton85.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton85.setText("jButton62");
        jPanel1.add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 60, 40));

        jButton91.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton91.setText("jButton62");
        jPanel1.add(jButton91, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 60, 40));

        jButton98.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton98.setText("jButton62");
        jPanel1.add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1120, 60, 40));

        jButton99.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton99.setText("jButton62");
        jPanel1.add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1120, 60, 40));

        jButton100.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton100.setText("jButton62");
        jPanel1.add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1120, 60, 40));

        jButton101.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton101.setText("jButton62");
        jPanel1.add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1120, 60, 40));

        jButton102.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton102.setText("jButton62");
        jPanel1.add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 1120, 60, 40));

        jButton103.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton103.setText("jButton62");
        jPanel1.add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 1120, 60, 40));

        jButton104.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton104.setText("jButton62");
        jPanel1.add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 940, 60, 40));

        jButton105.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton105.setText("jButton62");
        jPanel1.add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 940, 60, 40));

        jButton106.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton106.setText("jButton62");
        jPanel1.add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 940, 60, 40));

        jButton107.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton107.setText("jButton62");
        jPanel1.add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 940, 60, 40));

        jButton108.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton108.setText("jButton62");
        jPanel1.add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 940, 60, 40));

        jButton109.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user1.png"))); // NOI18N
        jButton109.setText("jButton62");
        jPanel1.add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 940, 60, 40));

        jButton73.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user2.png"))); // NOI18N
        jButton73.setText("jButton73");
        jButton73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton73ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton73, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 70, 50));

        jButton58.setBackground(new java.awt.Color(204, 0, 0));
        jButton58.setForeground(new java.awt.Color(204, 204, 204));
        jButton58.setText("more.....");
        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton58, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 220, 70, -1));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton87.setBackground(new java.awt.Color(0, 51, 51));
        jButton87.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton87.setForeground(new java.awt.Color(255, 204, 0));
        jButton87.setText("Technician");
        jPanel4.add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel5.setBackground(new java.awt.Color(0, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton88.setBackground(new java.awt.Color(0, 51, 51));
        jButton88.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton88.setForeground(new java.awt.Color(255, 204, 0));
        jButton88.setText("Technician");
        jPanel5.add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton89.setBackground(new java.awt.Color(0, 51, 51));
        jButton89.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton89.setForeground(new java.awt.Color(255, 204, 0));
        jButton89.setText("Technician");
        jPanel6.add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jButton36.setBackground(new java.awt.Color(0, 51, 51));
        jButton36.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton36.setForeground(new java.awt.Color(255, 204, 0));
        jButton36.setText("Maid");
        jPanel2.add(jButton36, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1040, 800, 50));

        jPanel3.setBackground(new java.awt.Color(0, 51, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton86.setBackground(new java.awt.Color(0, 51, 51));
        jButton86.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton86.setForeground(new java.awt.Color(255, 204, 0));
        jButton86.setText("Electrician");
        jButton86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton86ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 800, 50));

        jPanel7.setBackground(new java.awt.Color(0, 51, 51));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton90.setBackground(new java.awt.Color(0, 51, 51));
        jButton90.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton90.setForeground(new java.awt.Color(255, 204, 0));
        jButton90.setText("Technician");
        jPanel7.add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel8.setBackground(new java.awt.Color(0, 51, 51));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton92.setBackground(new java.awt.Color(0, 51, 51));
        jButton92.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton92.setForeground(new java.awt.Color(255, 204, 0));
        jButton92.setText("Technician");
        jPanel8.add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel9.setBackground(new java.awt.Color(0, 51, 51));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton93.setBackground(new java.awt.Color(0, 51, 51));
        jButton93.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton93.setForeground(new java.awt.Color(255, 204, 0));
        jButton93.setText("Technician");
        jPanel9.add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel10.setBackground(new java.awt.Color(0, 51, 51));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton94.setBackground(new java.awt.Color(0, 51, 51));
        jButton94.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton94.setForeground(new java.awt.Color(255, 204, 0));
        jButton94.setText("Technician");
        jPanel10.add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel9.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel7.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel11.setBackground(new java.awt.Color(0, 51, 51));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(0, 51, 51));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton95.setBackground(new java.awt.Color(0, 51, 51));
        jButton95.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton95.setForeground(new java.awt.Color(255, 204, 0));
        jButton95.setText("Technician");
        jPanel12.add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel11.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel13.setBackground(new java.awt.Color(0, 51, 51));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton96.setBackground(new java.awt.Color(0, 51, 51));
        jButton96.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton96.setForeground(new java.awt.Color(255, 204, 0));
        jButton96.setText("Technician");
        jPanel13.add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel14.setBackground(new java.awt.Color(0, 51, 51));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton97.setBackground(new java.awt.Color(0, 51, 51));
        jButton97.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton97.setForeground(new java.awt.Color(255, 204, 0));
        jButton97.setText("Technician");
        jPanel14.add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel13.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel11.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jButton28.setBackground(new java.awt.Color(0, 51, 51));
        jButton28.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton28.setForeground(new java.awt.Color(255, 204, 0));
        jButton28.setText("Cleaner");
        jPanel11.add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 50));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 800, 50));

        jPanel15.setBackground(new java.awt.Color(0, 51, 51));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel16.setBackground(new java.awt.Color(0, 51, 51));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton110.setBackground(new java.awt.Color(0, 51, 51));
        jButton110.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton110.setForeground(new java.awt.Color(255, 204, 0));
        jButton110.setText("Technician");
        jPanel16.add(jButton110, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel15.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel17.setBackground(new java.awt.Color(0, 51, 51));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton111.setBackground(new java.awt.Color(0, 51, 51));
        jButton111.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton111.setForeground(new java.awt.Color(255, 204, 0));
        jButton111.setText("Technician");
        jPanel17.add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel18.setBackground(new java.awt.Color(0, 51, 51));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton112.setBackground(new java.awt.Color(0, 51, 51));
        jButton112.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton112.setForeground(new java.awt.Color(255, 204, 0));
        jButton112.setText("Technician");
        jPanel18.add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel17.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel15.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jButton113.setBackground(new java.awt.Color(0, 51, 51));
        jButton113.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton113.setForeground(new java.awt.Color(255, 204, 0));
        jButton113.setText("Plumber");
        jButton113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton113ActionPerformed(evt);
            }
        });
        jPanel15.add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 800, 50));

        jPanel19.setBackground(new java.awt.Color(0, 51, 51));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(0, 51, 51));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton114.setBackground(new java.awt.Color(0, 51, 51));
        jButton114.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton114.setForeground(new java.awt.Color(255, 204, 0));
        jButton114.setText("Technician");
        jPanel20.add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel21.setBackground(new java.awt.Color(0, 51, 51));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton115.setBackground(new java.awt.Color(0, 51, 51));
        jButton115.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton115.setForeground(new java.awt.Color(255, 204, 0));
        jButton115.setText("Technician");
        jPanel21.add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel22.setBackground(new java.awt.Color(0, 51, 51));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton116.setBackground(new java.awt.Color(0, 51, 51));
        jButton116.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton116.setForeground(new java.awt.Color(255, 204, 0));
        jButton116.setText("Technician");
        jPanel22.add(jButton116, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 50));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 800, 50));

        jButton117.setBackground(new java.awt.Color(0, 51, 51));
        jButton117.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton117.setForeground(new java.awt.Color(255, 204, 0));
        jButton117.setText("Nurse");
        jPanel19.add(jButton117, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        jPanel1.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 860, 800, 50));

        jPanel23.setBackground(new java.awt.Color(51, 51, 51));

        jTextField3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextField3.setText("Hire and Payment");

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(620, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 1290, 810, 180));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1500, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Log_In obj = new Log_In();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        Index obj = new Index();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         Plumbing obj = new Plumbing();
        obj.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Maid obj = new Maid();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Nursing obj = new Nursing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        electrisian obj = new electrisian();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        // TODO add your handling code here:
        WorkerRegister obj = new WorkerRegister();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        // TODO add your handling code here:
        Tecnician obj = new Tecnician();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton30ActionPerformed
        // TODO add your handling code here:
        Hire obj = new Hire();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton30ActionPerformed

    private void jButton29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton29ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton73ActionPerformed
        // TODO add your handling code here:
        WorkerProfile obj = new WorkerProfile();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton73ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        // TODO add your handling code here:
        electrisian obj = new electrisian();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        // TODO add your handling code here:
        Tecnician obj = new Tecnician();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        // TODO add your handling code here:
        Plumbing obj = new Plumbing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        // TODO add your handling code here:
        Nursing obj = new Nursing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton33ActionPerformed
        // TODO add your handling code here:
        Maid obj = new Maid();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton33ActionPerformed

    private void jButton86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton86ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton86ActionPerformed

    private void jButton31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton31ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton113ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton113ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton110;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton116;
    private javax.swing.JButton jButton117;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JButton jButton73;
    private javax.swing.JButton jButton74;
    private javax.swing.JButton jButton75;
    private javax.swing.JButton jButton76;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton91;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
