/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.xemocode.demo;

/**
 *
 * @author Saif
 */
public class Plumbing extends javax.swing.JFrame {

    /**
     * Creates new form Plumbing
     */
    public Plumbing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jButton77 = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jButton79 = new javax.swing.JButton();
        jButton80 = new javax.swing.JButton();
        jButton81 = new javax.swing.JButton();
        jButton82 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextArea16 = new javax.swing.JTextArea();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextArea17 = new javax.swing.JTextArea();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextArea18 = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jButton83 = new javax.swing.JButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jButton84 = new javax.swing.JButton();
        jButton85 = new javax.swing.JButton();
        jButton86 = new javax.swing.JButton();
        jButton92 = new javax.swing.JButton();
        jButton93 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jButton94 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextArea19 = new javax.swing.JTextArea();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextArea20 = new javax.swing.JTextArea();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextArea21 = new javax.swing.JTextArea();
        jButton87 = new javax.swing.JButton();
        jButton95 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton96 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton97 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTextArea22 = new javax.swing.JTextArea();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTextArea23 = new javax.swing.JTextArea();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextArea24 = new javax.swing.JTextArea();
        jButton90 = new javax.swing.JButton();
        jButton98 = new javax.swing.JButton();
        jButton99 = new javax.swing.JButton();
        jButton100 = new javax.swing.JButton();
        jButton101 = new javax.swing.JButton();
        jButton102 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jScrollPane25 = new javax.swing.JScrollPane();
        jTextArea25 = new javax.swing.JTextArea();
        jScrollPane26 = new javax.swing.JScrollPane();
        jTextArea26 = new javax.swing.JTextArea();
        jScrollPane27 = new javax.swing.JScrollPane();
        jTextArea27 = new javax.swing.JTextArea();
        jButton103 = new javax.swing.JButton();
        jButton104 = new javax.swing.JButton();
        jButton105 = new javax.swing.JButton();
        jButton106 = new javax.swing.JButton();
        jButton107 = new javax.swing.JButton();
        jButton108 = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane28 = new javax.swing.JScrollPane();
        jTextArea28 = new javax.swing.JTextArea();
        jScrollPane29 = new javax.swing.JScrollPane();
        jTextArea29 = new javax.swing.JTextArea();
        jScrollPane30 = new javax.swing.JScrollPane();
        jTextArea30 = new javax.swing.JTextArea();
        jButton109 = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jButton112 = new javax.swing.JButton();
        jButton113 = new javax.swing.JButton();
        jButton114 = new javax.swing.JButton();
        jButton115 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(856, 1400));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton77.setText("Technological Service");
        jButton77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton77ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton77, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 88, -1, -1));

        jButton78.setText("Cleaner");
        jButton78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton78ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 88, -1, -1));

        jButton79.setText("Nurse");
        jButton79.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton79ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton79, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 88, -1, -1));

        jButton80.setText("Maid");
        jButton80.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton80ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton80, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 88, -1, -1));

        jButton81.setText("Plumbing");
        jButton81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton81ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton81, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 89, -1, 21));

        jButton82.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton82.setText("Log Out");
        jButton82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton82ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton82, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, -1, -1));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, 140));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 140));

        jTextArea16.setColumns(20);
        jTextArea16.setRows(5);
        jTextArea16.setText("Name: Ahmed\nAge: 25\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane16.setViewportView(jTextArea16);

        jPanel4.add(jScrollPane16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, 90));

        jTextArea17.setColumns(20);
        jTextArea17.setRows(5);
        jTextArea17.setText("Name: Sami\nAge: 28\nProfession: Plumber\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane17.setViewportView(jTextArea17);

        jPanel4.add(jScrollPane17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 220, 100));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 230, 140));

        jTextArea18.setColumns(20);
        jTextArea18.setRows(5);
        jTextArea18.setText("Name: Ali\nAge: 23\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane18.setViewportView(jTextArea18);

        jPanel4.add(jScrollPane18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 95));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/user2.png"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, -1, -1));

        jButton83.setBackground(new java.awt.Color(0, 153, 153));
        jButton83.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton83.setForeground(new java.awt.Color(255, 255, 255));
        jButton83.setText("Utility Service Provider");
        jButton83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton83ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton83, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 0, 760, 67));

        jToggleButton6.setText("Electrical Service");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 88, -1, -1));

        jButton84.setBackground(new java.awt.Color(204, 0, 0));
        jButton84.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton84.setForeground(new java.awt.Color(255, 255, 255));
        jButton84.setText("Hire Now");
        jButton84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton84ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton84, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 100, -1));

        jButton85.setBackground(new java.awt.Color(204, 0, 0));
        jButton85.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton85.setForeground(new java.awt.Color(255, 255, 255));
        jButton85.setText("Hire Now");
        jPanel4.add(jButton85, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 30));

        jButton86.setBackground(new java.awt.Color(204, 0, 0));
        jButton86.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton86.setForeground(new java.awt.Color(255, 255, 255));
        jButton86.setText("Hire Now");
        jPanel4.add(jButton86, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        jButton92.setBackground(new java.awt.Color(102, 0, 102));
        jButton92.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton92.setForeground(new java.awt.Color(255, 255, 255));
        jButton92.setText("more");
        jPanel4.add(jButton92, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jButton93.setBackground(new java.awt.Color(102, 0, 102));
        jButton93.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton93.setForeground(new java.awt.Color(255, 255, 255));
        jButton93.setText("more");
        jButton93.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton93ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton93, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 140));

        jButton94.setBackground(new java.awt.Color(102, 0, 102));
        jButton94.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton94.setForeground(new java.awt.Color(255, 255, 255));
        jButton94.setText("more");
        jPanel4.add(jButton94, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 230, 140));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 220, 140));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 220, 140));

        jTextArea19.setColumns(20);
        jTextArea19.setRows(5);
        jTextArea19.setText("Name: Sami\nAge: 28\nProfession: Plumber\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane19.setViewportView(jTextArea19);

        jPanel4.add(jScrollPane19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 220, 100));

        jTextArea20.setColumns(20);
        jTextArea20.setRows(5);
        jTextArea20.setText("Name: Ali\nAge: 23\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane20.setViewportView(jTextArea20);

        jPanel4.add(jScrollPane20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 590, -1, 95));

        jTextArea21.setColumns(20);
        jTextArea21.setRows(5);
        jTextArea21.setText("Name: Ahmed\nAge: 25\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane21.setViewportView(jTextArea21);

        jPanel4.add(jScrollPane21, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 590, -1, 90));

        jButton87.setBackground(new java.awt.Color(204, 0, 0));
        jButton87.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton87.setForeground(new java.awt.Color(255, 255, 255));
        jButton87.setText("Hire Now");
        jPanel4.add(jButton87, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 700, -1, -1));

        jButton95.setBackground(new java.awt.Color(102, 0, 102));
        jButton95.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton95.setForeground(new java.awt.Color(255, 255, 255));
        jButton95.setText("more");
        jPanel4.add(jButton95, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 700, -1, -1));

        jButton88.setBackground(new java.awt.Color(204, 0, 0));
        jButton88.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton88.setForeground(new java.awt.Color(255, 255, 255));
        jButton88.setText("Hire Now");
        jButton88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton88ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton88, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 700, 100, -1));

        jButton96.setBackground(new java.awt.Color(102, 0, 102));
        jButton96.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton96.setForeground(new java.awt.Color(255, 255, 255));
        jButton96.setText("more");
        jButton96.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton96ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton96, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 700, -1, -1));

        jButton89.setBackground(new java.awt.Color(204, 0, 0));
        jButton89.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton89.setForeground(new java.awt.Color(255, 255, 255));
        jButton89.setText("Hire Now");
        jPanel4.add(jButton89, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 700, -1, 30));

        jButton97.setBackground(new java.awt.Color(102, 0, 102));
        jButton97.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton97.setForeground(new java.awt.Color(255, 255, 255));
        jButton97.setText("more");
        jPanel4.add(jButton97, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 700, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, 230, 140));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 220, 140));

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 220, 140));

        jTextArea22.setColumns(20);
        jTextArea22.setRows(5);
        jTextArea22.setText("Name: Sami\nAge: 28\nProfession: Plumber\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane22.setViewportView(jTextArea22);

        jPanel4.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 220, 100));

        jTextArea23.setColumns(20);
        jTextArea23.setRows(5);
        jTextArea23.setText("Name: Ali\nAge: 23\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane23.setViewportView(jTextArea23);

        jPanel4.add(jScrollPane23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, 95));

        jTextArea24.setColumns(20);
        jTextArea24.setRows(5);
        jTextArea24.setText("Name: Ahmed\nAge: 25\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane24.setViewportView(jTextArea24);

        jPanel4.add(jScrollPane24, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, 90));

        jButton90.setBackground(new java.awt.Color(204, 0, 0));
        jButton90.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton90.setForeground(new java.awt.Color(255, 255, 255));
        jButton90.setText("Hire Now");
        jPanel4.add(jButton90, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, -1, -1));

        jButton98.setBackground(new java.awt.Color(153, 0, 153));
        jButton98.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton98.setForeground(new java.awt.Color(255, 255, 255));
        jButton98.setText("more");
        jPanel4.add(jButton98, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, -1, -1));

        jButton99.setBackground(new java.awt.Color(204, 0, 0));
        jButton99.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton99.setForeground(new java.awt.Color(255, 255, 255));
        jButton99.setText("Hire Now");
        jButton99.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton99ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton99, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 390, 100, -1));

        jButton100.setBackground(new java.awt.Color(102, 0, 102));
        jButton100.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton100.setForeground(new java.awt.Color(255, 255, 255));
        jButton100.setText("more");
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton100, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jButton101.setBackground(new java.awt.Color(204, 0, 0));
        jButton101.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton101.setForeground(new java.awt.Color(255, 255, 255));
        jButton101.setText("Hire Now");
        jPanel4.add(jButton101, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, 30));

        jButton102.setBackground(new java.awt.Color(102, 0, 102));
        jButton102.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton102.setForeground(new java.awt.Color(255, 255, 255));
        jButton102.setText("more");
        jPanel4.add(jButton102, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 770, 230, 140));

        jLabel33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 770, 220, 140));

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, 220, 140));

        jTextArea25.setColumns(20);
        jTextArea25.setRows(5);
        jTextArea25.setText("Name: Sami\nAge: 28\nProfession: Plumber\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane25.setViewportView(jTextArea25);

        jPanel4.add(jScrollPane25, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 920, 220, 100));

        jTextArea26.setColumns(20);
        jTextArea26.setRows(5);
        jTextArea26.setText("Name: Ali\nAge: 23\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane26.setViewportView(jTextArea26);

        jPanel4.add(jScrollPane26, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 920, -1, 95));

        jTextArea27.setColumns(20);
        jTextArea27.setRows(5);
        jTextArea27.setText("Name: Ahmed\nAge: 25\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane27.setViewportView(jTextArea27);

        jPanel4.add(jScrollPane27, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 920, -1, 90));

        jButton103.setBackground(new java.awt.Color(204, 0, 0));
        jButton103.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton103.setForeground(new java.awt.Color(255, 255, 255));
        jButton103.setText("Hire Now");
        jPanel4.add(jButton103, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1030, -1, -1));

        jButton104.setBackground(new java.awt.Color(102, 0, 102));
        jButton104.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton104.setForeground(new java.awt.Color(255, 255, 255));
        jButton104.setText("more");
        jPanel4.add(jButton104, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1030, -1, -1));

        jButton105.setBackground(new java.awt.Color(204, 0, 0));
        jButton105.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton105.setForeground(new java.awt.Color(255, 255, 255));
        jButton105.setText("Hire Now");
        jButton105.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton105ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton105, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1030, 100, -1));

        jButton106.setBackground(new java.awt.Color(102, 0, 102));
        jButton106.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton106.setForeground(new java.awt.Color(255, 255, 255));
        jButton106.setText("more");
        jButton106.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton106ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton106, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1030, -1, -1));

        jButton107.setBackground(new java.awt.Color(204, 0, 0));
        jButton107.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton107.setForeground(new java.awt.Color(255, 255, 255));
        jButton107.setText("Hire Now");
        jPanel4.add(jButton107, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1030, -1, 30));

        jButton108.setBackground(new java.awt.Color(102, 0, 102));
        jButton108.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton108.setForeground(new java.awt.Color(255, 255, 255));
        jButton108.setText("more");
        jPanel4.add(jButton108, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1030, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1090, 230, 140));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1090, 220, 140));

        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/xemocode/demo/icons/plumber.png"))); // NOI18N
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1090, 220, 140));

        jTextArea28.setColumns(20);
        jTextArea28.setRows(5);
        jTextArea28.setText("Name: Sami\nAge: 28\nProfession: Plumber\nExperience: 1years\nPrice: 100Tk per Hour");
        jScrollPane28.setViewportView(jTextArea28);

        jPanel4.add(jScrollPane28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1240, 220, 100));

        jTextArea29.setColumns(20);
        jTextArea29.setRows(5);
        jTextArea29.setText("Name: Ali\nAge: 23\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane29.setViewportView(jTextArea29);

        jPanel4.add(jScrollPane29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1240, -1, 95));

        jTextArea30.setColumns(20);
        jTextArea30.setRows(5);
        jTextArea30.setText("Name: Ahmed\nAge: 25\nProfession: Plumber\nExperience: 2years\nPrice: 100Tk per Hour");
        jScrollPane30.setViewportView(jTextArea30);

        jPanel4.add(jScrollPane30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1240, -1, 90));

        jButton109.setBackground(new java.awt.Color(204, 0, 0));
        jButton109.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton109.setForeground(new java.awt.Color(255, 255, 255));
        jButton109.setText("Hire Now");
        jPanel4.add(jButton109, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 1350, -1, -1));

        jButton111.setBackground(new java.awt.Color(204, 0, 0));
        jButton111.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton111.setForeground(new java.awt.Color(255, 255, 255));
        jButton111.setText("Hire Now");
        jButton111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton111ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 1350, 100, -1));

        jButton112.setBackground(new java.awt.Color(102, 0, 102));
        jButton112.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton112.setForeground(new java.awt.Color(255, 255, 255));
        jButton112.setText("more");
        jButton112.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton112ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton112, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 1350, -1, -1));

        jButton113.setBackground(new java.awt.Color(204, 0, 0));
        jButton113.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton113.setForeground(new java.awt.Color(255, 255, 255));
        jButton113.setText("Hire Now");
        jPanel4.add(jButton113, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 1350, -1, 30));

        jButton114.setBackground(new java.awt.Color(102, 0, 102));
        jButton114.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton114.setForeground(new java.awt.Color(255, 255, 255));
        jButton114.setText("more");
        jPanel4.add(jButton114, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 1350, -1, -1));

        jButton115.setBackground(new java.awt.Color(102, 0, 102));
        jButton115.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton115.setForeground(new java.awt.Color(255, 255, 255));
        jButton115.setText("more");
        jPanel4.add(jButton115, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 1350, -1, -1));

        jLabel1.setText("Next page");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 1460, 440, -1));

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton77ActionPerformed
        // TODO add your handling code here:
        Tecnician obj = new Tecnician();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton77ActionPerformed

    private void jButton78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton78ActionPerformed
        // TODO add your handling code here:
        Cleaner obj = new Cleaner();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton78ActionPerformed

    private void jButton79ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton79ActionPerformed
        // TODO add your handling code here:
        Nursing obj = new Nursing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton79ActionPerformed

    private void jButton80ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton80ActionPerformed
        // TODO add your handling code here:
        Maid obj = new Maid();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton80ActionPerformed

    private void jButton81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton81ActionPerformed
        // TODO add your handling code here:
        Plumbing obj = new Plumbing();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton81ActionPerformed

    private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton83ActionPerformed
        // TODO add your handling code here:
        Index obj = new Index();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton83ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        electrisian obj = new electrisian();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jButton82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton82ActionPerformed
        // TODO add your handling code here:
        Log_In obj = new Log_In();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton82ActionPerformed

    private void jButton84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton84ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton84ActionPerformed

    private void jButton93ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton93ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton93ActionPerformed

    private void jButton88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton88ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton88ActionPerformed

    private void jButton96ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton96ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton96ActionPerformed

    private void jButton99ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton99ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton99ActionPerformed

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton100ActionPerformed

    private void jButton105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton105ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton105ActionPerformed

    private void jButton106ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton106ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton106ActionPerformed

    private void jButton111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton111ActionPerformed

    private void jButton112ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton112ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton112ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Plumbing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Plumbing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Plumbing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Plumbing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Plumbing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton101;
    private javax.swing.JButton jButton102;
    private javax.swing.JButton jButton103;
    private javax.swing.JButton jButton104;
    private javax.swing.JButton jButton105;
    private javax.swing.JButton jButton106;
    private javax.swing.JButton jButton107;
    private javax.swing.JButton jButton108;
    private javax.swing.JButton jButton109;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton112;
    private javax.swing.JButton jButton113;
    private javax.swing.JButton jButton114;
    private javax.swing.JButton jButton115;
    private javax.swing.JButton jButton77;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButton79;
    private javax.swing.JButton jButton80;
    private javax.swing.JButton jButton81;
    private javax.swing.JButton jButton82;
    private javax.swing.JButton jButton83;
    private javax.swing.JButton jButton84;
    private javax.swing.JButton jButton85;
    private javax.swing.JButton jButton86;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JButton jButton92;
    private javax.swing.JButton jButton93;
    private javax.swing.JButton jButton94;
    private javax.swing.JButton jButton95;
    private javax.swing.JButton jButton96;
    private javax.swing.JButton jButton97;
    private javax.swing.JButton jButton98;
    private javax.swing.JButton jButton99;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JTextArea jTextArea16;
    private javax.swing.JTextArea jTextArea17;
    private javax.swing.JTextArea jTextArea18;
    private javax.swing.JTextArea jTextArea19;
    private javax.swing.JTextArea jTextArea20;
    private javax.swing.JTextArea jTextArea21;
    private javax.swing.JTextArea jTextArea22;
    private javax.swing.JTextArea jTextArea23;
    private javax.swing.JTextArea jTextArea24;
    private javax.swing.JTextArea jTextArea25;
    private javax.swing.JTextArea jTextArea26;
    private javax.swing.JTextArea jTextArea27;
    private javax.swing.JTextArea jTextArea28;
    private javax.swing.JTextArea jTextArea29;
    private javax.swing.JTextArea jTextArea30;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
}
